# Generated by Django 4.1.3 on 2022-11-06 13:17

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caloria',
            fields=[
                ('id_caloria', models.AutoField(db_column='ID_CALORIA', primary_key=True, serialize=False)),
                ('persona', models.CharField(choices=[('ADOLESCENTE', 'Adolescente'), ('ADULTO', 'Adulto'), ('ANCIANO', 'Anciano')], db_column='PERSONA', default=('ADOLESCENTE', 'Adolescente'), max_length=30, null=True)),
                ('genero', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], db_column='GENERO', default=('HOMBRE', 'Hombre'), max_length=30, null=True)),
                ('edad_min', models.IntegerField(blank=True, db_column='EDAD_MIN', null=True)),
                ('edad_max', models.IntegerField(blank=True, db_column='EDAD_MAX', null=True)),
                ('calorias', models.IntegerField(blank=True, db_column='CALORIAS', null=True)),
            ],
            options={
                'db_table': 'CALORIA',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'CATEGORIA',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'CATEGORIA_PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id_dieta', models.AutoField(db_column='ID_DIETA', primary_key=True, serialize=False)),
                ('lunes', ckeditor.fields.RichTextField(db_column='LUNES')),
                ('martes', ckeditor.fields.RichTextField(db_column='MARTES')),
                ('miercoles', ckeditor.fields.RichTextField(db_column='MIERCOLES')),
                ('jueves', ckeditor.fields.RichTextField(db_column='JUEVES')),
                ('viernes', ckeditor.fields.RichTextField(db_column='VIERNES')),
                ('sabado', ckeditor.fields.RichTextField(db_column='SABADO')),
                ('domingo', ckeditor.fields.RichTextField(db_column='DOMINGO')),
                ('kcal', models.ForeignKey(db_column='KCAL', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.caloria')),
            ],
            options={
                'db_table': 'DIETA',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='ID_ESTADO', primary_key=True, serialize=False)),
                ('minimo', models.DecimalField(db_column='MINIMO', decimal_places=1, max_digits=3)),
                ('maximo', models.DecimalField(db_column='MAXIMO', decimal_places=1, max_digits=3)),
                ('tipo', models.CharField(db_column='TIPO', max_length=45)),
                ('descripcion', ckeditor.fields.RichTextField(db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'ESTADO',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=45)),
            ],
            options={
                'db_table': 'ROL',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('edad', models.IntegerField(db_column='EDAD')),
                ('dni', models.CharField(db_column='DNI', max_length=11, null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=12, null=True)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=50, null=True)),
                ('localidad', models.CharField(db_column='LOCALIDAD', max_length=50, null=True)),
                ('provincia', models.CharField(choices=[('A Coruña', 'A Coruña'), ('Álava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almería', 'Almería'), ('Asturias', 'Asturias'), ('Ávila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Baleares', 'Baleares'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Cáceres', 'Cáceres'), ('Cádiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellón', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Córdoba', 'Córdoba'), ('Cuenca', 'Cuenca'), ('Girona', 'Girona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Gipuzkoa', 'Gipuzkoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Jaén', 'Jaén'), ('La Rioja', 'La Rioja'), ('Las Palmas', 'Las Palmas'), ('León', 'León'), ('Lérida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Málaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Ourense', 'Ourense'), ('Palencia', 'Palencia'), ('Pontevedra', 'Pontevedra'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza')], db_column='PROVINCIA', max_length=30, null=True)),
                ('cp', models.CharField(db_column='CP', max_length=5, null=True)),
                ('peso', models.IntegerField(db_column='PESO')),
                ('altura', models.DecimalField(db_column='ALTURA', decimal_places=2, max_digits=3)),
                ('imc', models.DecimalField(blank=True, db_column='IMC', decimal_places=1, max_digits=3, null=True)),
                ('genero', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], db_column='GENERO', default=('HOMBRE', 'Hombre'), max_length=30)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True)),
                ('dieta', models.ManyToManyField(blank=True, db_column='DIETA', to='NaturadietApp.dieta')),
                ('estado', models.ForeignKey(blank=True, db_column='ESTADO', null=True, on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.estado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(db_column='ROL', default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USUARIO',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=255)),
                ('imagen', models.ImageField(db_column='IMAGEN', upload_to='Productos')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
                ('precio', models.DecimalField(db_column='PRECIO', decimal_places=2, max_digits=5)),
                ('disponibilidad', models.BooleanField(db_column='DISPONIBILIDAD', default=True)),
                ('categoria', models.ForeignKey(db_column='CATEGORIA', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.categoriaproducto')),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='ID_PEDIDO', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='FECHA')),
                ('total', models.DecimalField(blank=True, db_column='IMPORTE', decimal_places=2, max_digits=5, null=True)),
                ('entregado', models.BooleanField(db_column='ENTREGADO', default=False)),
                ('usuario', models.ForeignKey(db_column='USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(db_column='ID_NOTICIA', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=255)),
                ('subtitulo', models.CharField(db_column='SUBTITULO', max_length=255)),
                ('imagen', models.ImageField(db_column='IMAGEN', upload_to='Noticias')),
                ('contenido', ckeditor.fields.RichTextField(db_column='CONTENIDO', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='CREATED')),
                ('categoria', models.ForeignKey(db_column='CATEGORIA', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.categoria')),
                ('usuario', models.ForeignKey(db_column='USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NOTICIA',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(blank=True, db_column='IMPORTE', decimal_places=2, max_digits=5, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='CANTIDAD', null=True)),
                ('pedido', models.ForeignKey(db_column='PEDIDO', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.pedido')),
                ('producto', models.ForeignKey(db_column='PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.producto')),
            ],
            options={
                'db_table': 'FACTURA',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
